### ISSUE TITLE
Changelog shows 0.6.0 but releases show 0.4.0

### ISSUE THREAD

**Issue by zanco** [maia-sdr/plutosdr-fw#8]
quote "Update Maia SDR to v0.6.0. Add spectrometer peak detect mode."

I guess this should read 0.4.0 ?

**Comment by daniestevez** [comment]
There are independent version numbers for Maia SDR itself and for the Maia SDR Pluto firmware image. There is more info about this in the changelog:
> Semantic versioning for the firmware image is based on the user-facing features. A major version change involves new user features. There might be changes in Maia SDR that cause a major version change because of API changes but only cause a minor version change in the firmware image because from the point of view of the user the features have not changed significantly.

**Comment by daniestevez** [comment]
Closing as solved.
